##In this program, the user must try to guess a random number generated by the computer
from random import randint
def guess_game():
    """ A function to check whether the number guessed by the user matches the number generated by computer"""
    
    while True:
        random_num = randint(0,10)
        print random_num
        guess = int(raw_input(("Enter a number: ")))
        print guess
        if random_num == guess:
            print "your guess is correct"
            break
        else:
            print "Try Again"

guess_game()
